### ISSUE TITLE
Possible Denial of Service issue

### ISSUE THREAD

**Issue by yadij** [Hopbox/charcoal-helper#3]
This helper currently creates a new IO::Socket::INET to the backend service API for each line it receives from Squid, and explicitly closes it when completed.

If that object opens a new TCP socket for each such occurance it becomes possible for a busy proxy to run out of available TCP resources within a few seconds. This makes the helper a point of vulnerability for external attackers to DoS the whole machine Squid is operating on.

Squid does contain some mechanisms to harden against this type of attack, but these can only delay the inevitable collapse and add some slight level of difficulty to the attack - not prevent it entirely.

To do their part protecting against this issue helpers should limit the amount of connections made to their backend. Preferring to perform some reasonable amount query pipelining (especially when under high loads) instead of using a new socket for each transaction.
 Numbers to keep in mind when designing this vulnerability protection are that current Squid can deliver up to 25k queries per second, TCP sockets usual cool-down is several minutes and may be as large as 15min, with a pool of 64k total sockets shared between all helpers and Squid itself. Obviously there is a seriously large gap between available sockets and potential queries over the cooldown period.

**Comment by codemarauder** [comment]
This needs to be worked upon with the behaviour of the server. Server is closing connection on second request on the same connection.

This bug is dependent on Charcoal Server bug https://github.com/Hopbox/charcoal/issues/2

**Comment by codemarauder** [comment]
The server had to close connection after every request due to a bug in DBD::Pg. Upgraded to DBD::Pg 3.6.2 and server is able hold on to client connections for multiple queries.

With this commit (https://github.com/Hopbox/charcoal-helper/commit/2cd3a0f985c2083046267eee82f6c7df16113113), helper captures (ESTABLISHED & CLOSE_WAIT) only as many sockets as number of children run by squid as shown by netstat.

We want to explore the possibility of being able to create a  "connection-pool" to the server and share that pool amongst the children.
